replace structure
itomofumi/echo_starter_test pull request #12
Opened 2021-02-05 10:07 UTC by yutacoffee

リクエストの構造体を内部専用の構造体に入れ替える作業をしていますが、
DELETE()で詰まっています。

2021-02-05 11:16 UTC, itomofumi requested changes

2021-02-05 11:16 UTC, itomofumi commented on service/users.go
>  	if !ok {
`	ok := u.repo.Delete(model.Users{ID: param.ID})`
こんな感じでかけます

値が多いなら明示するためにこんな風に書いたりします

```
input := model.Users{
		ID: param.ID,
	}
	ok := u.repo.Delete(input)

```

2021-02-07 03:08 UTC, yutacoffee commented on service/users.go
>  	if !ok {
教えていただいた通りのコードに変更し、DELETE()に関して完了することができました。
ありがとうございます。

2021-02-08 09:26 UTC, itomofumi commented
コンフリクト解消お願いします

2021-02-08 09:36 UTC, itomofumi approved these changes
OKです

2021-02-08 09:36 UTC, merged