Feature/train2020 12
itomofumi/echo_starter_test pull request #16
Opened 2021-02-10 08:56 UTC by yutacoffee

carMaker の CRUDを実装しました。

2021-02-10 09:08 UTC, itomofumi requested changes

2021-02-10 09:08 UTC, itomofumi commented on .env.example
master マージ時にミスで不要な文字列がはいってます。

2021-02-10 09:35 UTC, itomofumi requested changes

2021-02-10 09:35 UTC, itomofumi commented on handler/car_maker.go
> +
パラメータ一１つでここまで改行すると逆にみにくいので以下のように指定するようにしてください

```
id := c.Param("id")
i, _ := strconv.Atoi(id
carMakers, err := carMakersService.GetCarMaker(param{ID: i})
```

2021-02-10 09:35 UTC, itomofumi commented on handler/car_maker.go
> +
ほかの箇所もそのようになるように

2021-02-10 09:35 UTC, itomofumi commented on handler/car_maker.go
> +		c.JSON(http.StatusInternalServerError, "fail")
エラーチェックで改行しない、直下に記述する

users, err := carMakersService.Update(param)
if err != nil {

2021-02-10 09:35 UTC, itomofumi commented on handler/car_maker.go
> +
自分ならこう書きます

```
func DeleteCarMaker(c echo.Context) error {
	factory := c.Get(factory.ServiceKey).(factory.Servicer)
	carMakersService := factory.NewCarMakers()
	id := c.Param("id")
	
　　var param request.DeleteCarMakerRequestParam
	param.ID, _ := strconv.Atoi(id)
	ok := carMakersService.DeleteCarMakers(param)

	if !ok {
		c.JSON(http.StatusInternalServerError, "fail")
	}
```

2021-02-10 09:35 UTC, itomofumi commented on repository/car_maker.go
> +	_, err := cm.engine.
固定値ではなく外部から設定できるようにしてください。
carMakers.About = "aaaaa"

2021-02-10 09:35 UTC, itomofumi commented on handler/cars.go
> +	factory := c.Get(factory.ServiceKey).(factory.Servicer)
UpdateVehicleType
↓
UpdateCar

2021-02-10 09:35 UTC, itomofumi commented on server/routes.go
> +	{
//car maker
↓
// car maker

2021-02-10 10:04 UTC, yutacoffee commented on handler/cars.go
> +	factory := c.Get(factory.ServiceKey).(factory.Servicer)
修正しました

2021-02-10 10:04 UTC, yutacoffee commented on server/routes.go
> +	{
修正しました

2021-02-10 10:05 UTC, yutacoffee commented on handler/car_maker.go
> +		c.JSON(http.StatusInternalServerError, "fail")
修正しました

2021-02-10 10:05 UTC, yutacoffee commented on handler/car_maker.go
> +
修正しました

2021-02-11 12:58 UTC, yutacoffee commented on repository/car_maker.go
> +	_, err := cm.engine.
user・car・car＿makerにて同様の箇所を修正しました

2021-02-12 07:41 UTC, itomofumi approved these changes

2021-02-12 07:42 UTC, merged